services:
  - type: web
    name: tailoring-web-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: FRONTEND_BASE_URL
        sync: false
